const testPreset = {
  _id: "Uso Ricreativo",
  header: {
    med2: "Uso Ricreativo",
    med2_key: "Uso Ricreativo",
    onlyOnce: false,
    d: 900,
    isShownIndex: -1,
    vcontrol: true,
    creator: "fabbri",
    communionSchedule: false,
  },
  voices: [
    {
      id: 1.2,
      mf0: 250,
      waveformM: 0,
      ma: 90,
      mp0: 10,
      mp1: 20,
      md: 600,
      type: "Martigli",
      panOsc: 0,
      panOscPeriod: 120,
      panOscTrans: 20,
      isOn: true,
      iniVolume: null,
    },
    {
      fl: 250,
      waveformL: 0,
      fr: 285,
      waveformR: 0,
      ma: 90,
      mp0: 10,
      mp1: 20,
      md: 850,
      type: "Martigli-Binaural",
      panOsc: 3,
      panOscPeriod: 120,
      panOscTrans: 20,
      isOn: true,
      iniVolume: null,
    },
    {
      id: 1,
      fl: 340,
      waveformL: 0,
      fr: 160,
      waveformR: 0,
      type: "Binaural",
      panOsc: 1,
      panOscPeriod: 120,
      panOscTrans: 20,
      iniVolume: null,
    },
    // {
    //   id: 2,
    //   nnotes: 50,
    //   noctaves: 2,
    //   f0: 200,
    //   d: 10,
    //   waveform: 0,
    //   permfunc: 1,
    //   type: "Symmetry",
    //   iniVolume: null,
    // },
    // {
    //   id: 3,
    //   nnotes: 50,
    //   noctaves: 2,
    //   f0: 203.1433133,
    //   d: 10,
    //   waveform: 0,
    //   permfunc: 2,
    //   type: "Symmetry",
    //   iniVolume: null,
    // },
    // {
    //   nnotes: 2,
    //   noctaves: 2,
    //   f0: 200,
    //   d: 1,
    //   waveform: 0,
    //   permfunc: 0,
    //   type: "Symmetry",
    //   iniVolume: null,
    // },
    // {
    //   nnotes: 2,
    //   noctaves: 2,
    //   f0: 200,
    //   d: 1,
    //   waveform: 0,
    //   permfunc: 0,
    //   type: "Symmetry",
    //   iniVolume: null,
    // },
  ],
};