// ============================================
// SESSION PRESETS FOR AVS SYSTEM
// ============================================
// Each preset contains a voices array that defines the audio configuration
// Duration (d) is in seconds, default 900s (15 minutes)
// visSettings are preserved for future visual features
// ============================================

const PRESETS = {
  // ========== RELAXATION & MEDITATION ==========

  Meditazione: {
    _id: "Meditazione",
    header: {
      med2: "Meditazione",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 1,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#D68C45",
      bgc: "#FEFEE3",
      fgc: "#4C956C",
      ccc: "#2C6E49",
      lcc: "#FFC9B9",
    },
    voices: [
      {
        type: "Symmetry",
        nnotes: 2,
        noctaves: 2,
        f0: 200,
        d: 1,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 2,
        noctaves: 2,
        f0: 200,
        d: 1,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Martigli-Binaural",
        fl: 150,
        fr: 159,
        waveformL: 0,
        waveformR: 0,
        ma: 120,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 140,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Martigli-Binaural",
        fl: 359,
        fr: 350,
        waveformL: 0,
        waveformR: 0,
        ma: 120,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: false,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 453,
        fr: 450,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 160,
        panOscTrans: 20,
        iniVolume: null,
      },
    ],
  },

  Rilassamento: {
    _id: "Rilassamento",
    header: {
      med2: "Rilassamento",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 3,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#83C5BE",
      bgc: "#006D77",
      fgc: "#EDF6F9",
      ccc: "#FFDDD2",
      lcc: "#E29578",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 253,
        fr: 250,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 30,
        panOscTrans: 0.5,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 535,
        fr: 526,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 20,
        panOscTrans: 1,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 7,
        noctaves: 2,
        f0: 100.1,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 7,
        noctaves: 2,
        f0: 100,
        d: 100,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 390,
        fr: 399,
        waveformL: 0,
        waveformR: 0,
        panOsc: 2,
        panOscPeriod: 0.333333333,
        panOscTrans: 20,
        iniVolume: null,
      },
    ],
  },

  // ========== FOCUS & PRODUCTIVITY ==========

  "Lavoro Focalizzato": {
    _id: "Lavoro Focalizzato",
    header: {
      med2: "Lavoro Focalizzato",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 31,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 2,
      bcc: "#000000",
      bgc: "#14213D",
      fgc: "#FCA311",
      ccc: "#E5E5E5",
      lcc: "#FFFFFF",
    },
    voices: [
      {
        type: "Binaural",
        fl: 150,
        fr: 190,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 100,
        panOscTrans: 20,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 495,
        fr: 455,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 20,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 6,
        noctaves: 2,
        f0: 100,
        d: 100,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 7,
        noctaves: 2,
        f0: 100.2,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Martigli-Binaural",
        fl: 270,
        fr: 280,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 150,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
    ],
  },

  "Guadagno QI": {
    _id: "Guadagno QI",
    header: {
      med2: "Guadagno QI",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 5,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 2,
      bcc: "#264653",
      bgc: "#2A9D8F",
      fgc: "#E9C46A",
      ccc: "#F4A261",
      lcc: "#E76F51",
    },
    voices: [
      {
        type: "Binaural",
        fl: 495,
        fr: 455,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 20,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 5,
        noctaves: 2,
        f0: 200,
        d: 100,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 5,
        noctaves: 2,
        f0: 210,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Martigli-Binaural",
        fl: 240,
        fr: 280,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 150,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
    ],
  },

  // ========== STUDY SESSIONS ==========

  "Studio Rilassante": {
    _id: "Studio Rilassante",
    header: {
      med2: "Studio Rilassante",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 7,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#F6BD60",
      bgc: "#F7EDE2",
      fgc: "#F5CAC3",
      ccc: "#84A59D",
      lcc: "#F28482",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 350,
        fr: 359,
        waveformL: 0,
        waveformR: 0,
        ma: 120,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 10,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 209,
        fr: 200,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 70,
        panOscTrans: 5,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 12,
        noctaves: 1,
        f0: 201,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
    ],
  },

  "Studio Energizzante": {
    _id: "Studio Energizzante",
    header: {
      med2: "Studio Energizzante",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 8,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 1,
      bcc: "#219EBC",
      bgc: "#023047",
      fgc: "#8ECAE6",
      ccc: "#FFB703",
      lcc: "#FB8500",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 350,
        fr: 360,
        waveformL: 0,
        waveformR: 0,
        ma: 120,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 10,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 240,
        fr: 200,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 70,
        panOscTrans: 5,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 12,
        noctaves: 2,
        f0: 201,
        d: 400,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
    ],
  },

  // ========== THERAPEUTIC ==========

  "Ansia e Depressione": {
    _id: "Ansia e Depressione",
    header: {
      med2: "Ansia e Depressione",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 4,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#CBF3F0",
      bgc: "#2EC4B6",
      fgc: "#FFFFFF",
      ccc: "#FFBF69",
      lcc: "#FF9F1C",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 203,
        fr: 200,
        waveformL: 0,
        waveformR: 0,
        ma: 160,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 300,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 335,
        fr: 326,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 200,
        panOscTrans: 1,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 7,
        noctaves: 2,
        f0: 150.1,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 9,
        noctaves: 2,
        f0: 150,
        d: 100,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 449.1666,
        fr: 458.166666,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 100,
        panOscTrans: 20,
        iniVolume: null,
      },
    ],
  },

  Insonnia: {
    _id: "Insonnia",
    header: {
      med2: "Insonnia",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 6,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#0077B6",
      bgc: "#03045E",
      fgc: "#00B4D8",
      ccc: "#90E0EF",
      lcc: "#CAF0F8",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 253,
        fr: 255.5,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 531,
        fr: 526,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 200,
        panOscTrans: 10,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 5,
        noctaves: 3,
        f0: 100.1,
        d: 64,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 5,
        noctaves: 3,
        f0: 100,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 397.5,
        fr: 399,
        waveformL: 0,
        waveformR: 0,
        panOsc: 2,
        panOscPeriod: 0.333333333,
        panOscTrans: 20,
        iniVolume: null,
      },
    ],
  },

  Dipendenza: {
    _id: "Dipendenza",
    header: {
      med2: "Dipendenza",
      d: 900,
      vcontrol: true,
      creator: "who",
    },
    visSetting: {
      lemniscate: 7,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#D8E2DC",
      bgc: "#FFE5D9",
      fgc: "#FFCAD4",
      ccc: "#F4ACB7",
      lcc: "#9D8189",
    },
    voices: [
      {
        type: "Martigli",
        mf0: 300,
        waveformM: 0,
        ma: 100,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 0,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Martigli",
        mf0: 300,
        waveformM: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 0,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: false,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 150,
        fr: 159,
        waveformL: 0,
        waveformR: 0,
        panOsc: 0,
        panOscPeriod: 120,
        panOscTrans: 20,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 7,
        noctaves: 3,
        f0: 100,
        d: 120,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 8,
        noctaves: 3,
        f0: 100,
        d: 130,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
    ],
  },

  // ========== PAIN MANAGEMENT ==========

  "Dolori Cronici": {
    _id: "Dolori Cronici",
    header: {
      med2: "Dolori Cronici",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 2,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#B388EB",
      bgc: "#8093F1",
      fgc: "#72DDF7",
      ccc: "#F7AEF8",
      lcc: "#FDC5F5",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 350,
        fr: 359.14,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 140,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 126.125,
        fr: 125,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 180,
        panOscTrans: 15,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 9,
        noctaves: 3,
        f0: 101,
        d: 160,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
    ],
  },

  Emicrania: {
    _id: "Emicrania",
    header: {
      med2: "Emicrania",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 6,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 0,
      bcc: "#028090",
      bgc: "#05668D",
      fgc: "#00A896",
      ccc: "#02C39A",
      lcc: "#F0F3BD",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 250,
        fr: 259,
        waveformL: 0,
        waveformR: 0,
        ma: 140,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 1,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Binaural",
        fl: 126.125,
        fr: 125,
        waveformL: 0,
        waveformR: 0,
        panOsc: 1,
        panOscPeriod: 140,
        panOscTrans: 5,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 9,
        noctaves: 2,
        f0: 201,
        d: 160,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 9,
        noctaves: 2,
        f0: 200,
        d: 40,
        waveform: 0,
        permfunc: 0,
        iniVolume: null,
      },
    ],
  },

  // ========== RECREATIONAL ==========

  "Uso Ricreativo": {
    _id: "Uso Ricreativo",
    header: {
      med2: "Uso Ricreativo",
      d: 900,
      vcontrol: true,
      creator: "fabbri",
    },
    visSetting: {
      lemniscate: 3,
      rainbowFlakes: false,
      ellipse: true,
      bPos: 2,
      bcc: "#2B2D42",
      bgc: "#8D99AE",
      fgc: "#EDF2F4",
      ccc: "#EF233C",
      lcc: "#D90429",
    },
    voices: [
      {
        type: "Martigli-Binaural",
        fl: 250,
        fr: 255,
        waveformL: 0,
        waveformR: 0,
        ma: 130,
        mp0: 10,
        mp1: 20,
        md: 600,
        panOsc: 0,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: true,
        iniVolume: null,
      },
      {
        type: "Martigli-Binaural",
        fl: 150,
        fr: 155,
        waveformL: 0,
        waveformR: 0,
        ma: 120,
        mp0: 0.02,
        mp1: 0.002,
        md: 850,
        panOsc: 3,
        panOscPeriod: 120,
        panOscTrans: 20,
        isOn: false,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 50,
        noctaves: 2,
        f0: 200,
        d: 10,
        waveform: 0,
        permfunc: 1,
        iniVolume: null,
      },
      {
        type: "Symmetry",
        nnotes: 50,
        noctaves: 2,
        f0: 203.1433133,
        d: 10,
        waveform: 0,
        permfunc: 2,
        iniVolume: null,
      },
    ],
  },
};

// ============================================
// EXPORTS
// ============================================

// Array of all presets for iteration
export const presetList = Object.values(PRESETS);

// Object with preset names as keys for direct access
export const presets = PRESETS;

// Legacy export for backward compatibility
export const audiovisualPresets = PRESETS;
export const audiovisualPresetsList = presetList;
